# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(586, 417)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        self.pageList = QtWidgets.QStackedWidget(self.centralwidget)
        self.pageList.setAutoFillBackground(True)
        self.pageList.setObjectName("pageList")
        self.treePage = QtWidgets.QWidget()
        self.treePage.setAutoFillBackground(True)
        self.treePage.setObjectName("treePage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.treePage)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tree_json = QtWidgets.QTreeWidget(self.treePage)
        self.tree_json.setAutoFillBackground(True)
        self.tree_json.setStyleSheet("\n"
" QTreeView::item:hover{background-color:rgb(0,255,0,50)} \n"
"QTreeView::item:selected{background-color:rgb(255,0,0,100)}\n"
"QTreeView::item{\n"
"height:30px\n"
"}")
        self.tree_json.setAutoScroll(True)
        self.tree_json.setObjectName("tree_json")
        self.gridLayout_2.addWidget(self.tree_json, 0, 0, 1, 1)
        self.pageList.addWidget(self.treePage)
        self.pathTree = QtWidgets.QWidget()
        self.pathTree.setAutoFillBackground(True)
        self.pathTree.setObjectName("pathTree")
        self.path_json = QtWidgets.QTextEdit(self.pathTree)
        self.path_json.setGeometry(QtCore.QRect(3, 19, 261, 61))
        self.path_json.setAutoFillBackground(True)
        self.path_json.setObjectName("path_json")
        self.pageList.addWidget(self.pathTree)
        self.formatPage = QtWidgets.QWidget()
        self.formatPage.setAutoFillBackground(True)
        self.formatPage.setObjectName("formatPage")
        self.format_json = QtWidgets.QTextEdit(self.formatPage)
        self.format_json.setGeometry(QtCore.QRect(3, 9, 261, 351))
        self.format_json.setAutoFillBackground(True)
        self.format_json.setObjectName("format_json")
        self.pageList.addWidget(self.formatPage)
        self.gridLayout.addWidget(self.pageList, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 586, 23))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_tool = QtWidgets.QMenu(self.menubar)
        self.menu_tool.setObjectName("menu_tool")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menubar)
        self.action_newFile = QtWidgets.QAction(MainWindow)
        self.action_newFile.setObjectName("action_newFile")
        self.action_openFile = QtWidgets.QAction(MainWindow)
        self.action_openFile.setObjectName("action_openFile")
        self.action_openBash = QtWidgets.QAction(MainWindow)
        self.action_openBash.setObjectName("action_openBash")
        self.action_beautifulJSON = QtWidgets.QAction(MainWindow)
        self.action_beautifulJSON.setObjectName("action_beautifulJSON")
        self.action_helpJSONDoc = QtWidgets.QAction(MainWindow)
        self.action_helpJSONDoc.setObjectName("action_helpJSONDoc")
        self.action_helpUse = QtWidgets.QAction(MainWindow)
        self.action_helpUse.setObjectName("action_helpUse")
        self.action_otherSaveFile = QtWidgets.QAction(MainWindow)
        self.action_otherSaveFile.setObjectName("action_otherSaveFile")
        self.action_saveFile = QtWidgets.QAction(MainWindow)
        self.action_saveFile.setObjectName("action_saveFile")
        self.action_JSONPath = QtWidgets.QAction(MainWindow)
        self.action_JSONPath.setObjectName("action_JSONPath")
        self.action_JSONTree = QtWidgets.QAction(MainWindow)
        self.action_JSONTree.setObjectName("action_JSONTree")
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_newFile)
        self.menu_file.addAction(self.action_openFile)
        self.menu_file.addAction(self.action_saveFile)
        self.menu_file.addAction(self.action_otherSaveFile)
        self.menu_tool.addSeparator()
        self.menu_tool.addAction(self.action_openBash)
        self.menu_tool.addAction(self.action_beautifulJSON)
        self.menu_tool.addAction(self.action_JSONPath)
        self.menu_tool.addAction(self.action_JSONTree)
        self.menu_help.addAction(self.action_helpJSONDoc)
        self.menu_help.addAction(self.action_helpUse)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_tool.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        self.pageList.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "在此编辑，粘贴，打开JSON"))
        self.path_json.setPlaceholderText(_translate("MainWindow", "请输入JSONPath"))
        self.format_json.setPlaceholderText(_translate("MainWindow", "格式化后的字符串"))
        self.menu_file.setTitle(_translate("MainWindow", "文件"))
        self.menu_tool.setTitle(_translate("MainWindow", "工具"))
        self.menu_help.setTitle(_translate("MainWindow", "帮助"))
        self.action_newFile.setText(_translate("MainWindow", "新建JSON文件"))
        self.action_openFile.setText(_translate("MainWindow", "打开JSON文件"))
        self.action_openBash.setText(_translate("MainWindow", "打开命令行工具"))
        self.action_beautifulJSON.setText(_translate("MainWindow", "格式化JSON"))
        self.action_helpJSONDoc.setText(_translate("MainWindow", "JSON文档帮助"))
        self.action_helpUse.setText(_translate("MainWindow", "使用帮助"))
        self.action_otherSaveFile.setText(_translate("MainWindow", "另存"))
        self.action_saveFile.setText(_translate("MainWindow", "保存"))
        self.action_saveFile.setStatusTip(_translate("MainWindow", "Ctrl + S"))
        self.action_JSONPath.setText(_translate("MainWindow", "JSONPath"))
        self.action_JSONTree.setText(_translate("MainWindow", "JSONTree"))

